export const START_FETCHING_PARTICIPANTS = 'redux/participants/START_FETCHING_PARTICIPANTS';
export const SUCCESS_FETCHING_PARTICIPANTS =
  'redux/participants/SUCCESS_FETCHING_PARTICIPANTS';
export const ERROR_FETCHING_PARTICIPANTS = 'redux/participants/ERROR_FETCHING_PARTICIPANTS';

